### ISSUE TITLE
NRS Station Info

### ISSUE THREAD

**Issue by jaseeverett** [PlanktonTeam/IMOS_Toolbox#11]
@clairedavies I think we should create a file which contains all the generic info for the NRS stations - Name, Abbreviation, depth, lat/lon etc. That way someone who wants to make a map, can easily load and plot and label them. It should be easy to do it in conjunction with the zooplankton indices file.

**Comment by jaseeverett** [comment]
Here is a start from the SOE2021 code

```
NRS <- read_csv(paste0("Data",.Platform$file.sep,"NRS_Indices.csv")) %>%
  group_by(Station) %>%
  mutate(Year_Start = min(Year),
         Year_Latest = max(Year)) %>%
  ungroup() %>%
  distinct(Station, .keep_all = TRUE) %>%
  dplyr::select(NRScode, Station, Latitude, Longitude, StationDepth_m, Year_Start, Year_Latest)
```

**Comment by clairedavies** [comment]
Or we reference the station table (which has all this info, plus IMCRA regions, bioregions, depths etc. ) from the AODN when they host the base tables that we make the products from ……

**Comment by jaseeverett** [comment]
That sounds good. 
Is that a table you can easily extract and add to the `RawData/*.csv` files here?

**Comment by clairedavies** [comment]
done

**Comment by jaseeverett** [comment]
Great. Thanks. I will have a look and write some code to extract it into a nibble.

**Comment by jaseeverett** [comment]
Code now exists for this.
