### ISSUE TITLE
Start to compile indices of MLD, Zeu, Kd etc

### ISSUE THREAD

**Issue by jaseeverett** [PlanktonTeam/IMOS_Toolbox#12]

**Comment by clairedavies** [comment]
Methods in literature folder with data as per PVR calculations (for checking only).
Fig 8 in Holte & Talley 2009.
DCM was simply max fluorescence value from CTD.

**Comment by clairedavies** [comment]
And plankton/rawdata/nrs_ctd.csv is the latest CTD data.

**Comment by clairedavies** [comment]
This has been done for NRS and added to indices products
