### ISSUE TITLE
Naming of Sapphirina ovatolanceolata / gemma in CPR_Zoop_Raw.csv

### ISSUE THREAD

**Issue by PhDyellow** [PlanktonTeam/IMOS_Toolbox#15]
I recently had some issues with one particular species CPR_Zoop_Raw.csv:
```
305-61,Sapphirina ovatolanceolata / gemma f,COPEPOD,Copepod,Sapphirina,ovatolanceolata/ gemma,129055,0.6667
```
The species column is `ovatolanceolata/ gemma`, which is missing a space between `ovatolanceolata` and `/`.
@clairedavies, some of the scripts you sent me extracted the first word of the species, and pulled in the `/`, which broke R in places when converted to a column name.

I don't need a fix myself, I will add some more filters to my pipeline, but I am adding this as an issue in case it matters elsewhere.

**Comment by clairedavies** [comment]
Species name corrected in database.
Files for NRS and CPR zooplankton rerun and products remade, should solve this issue
This taxa should not actual be in the species files as it is not a definite id. Stays in the raw data and users can decide.
