### ISSUE TITLE
NRS_CTD.csv file - column castTime_Local is defaulting to UTC

### ISSUE THREAD

**Issue by Abulos** [PlanktonTeam/IMOS_Toolbox#16]
https://github.com/PlanktonTeam/IMOS_Toolbox/blob/e99561b0554dbec69b43d1b68c2a440645c9b7ce/Plankton/IMOS_Plankton_functions.R#L175

function with_tz parameters are: time and tzone (not tz).
function with_tz is set to "Australia/Perth"

**Comment by jaseeverett** [comment]
@clairedavies can you look at this?

**Comment by clairedavies** [comment]
Thanks for the comment, that was a placeholder that I never got round to changing, It has been fixed now, tz isn't as flexible as I thought, reverted to format() instead.
