### ISSUE TITLE
Incorrect variable name

### ISSUE THREAD

**Issue by jaseeverett** [PlanktonTeam/IMOS_Toolbox#18]
@clairedavies 
with the last data update, `TAXON_NAME` was changed to `TAXONNAME` in `IMOS_Toolbox/Plankton/RawData/CPR_Phyto_ChangeLog.csv`

`TAXONNAME` is inconsistent with other data files. Suggest changing back

**Comment by clairedavies** [comment]
All taxonnames should have now been removed. Functions will need updating accordingly
