### ISSUE TITLE
Problems with BGC_TSS.csv

### ISSUE THREAD

**Issue by jaseeverett** [PlanktonTeam/IMOS_Toolbox#23]
@clairedavies I know you said BGC_TSS.csv is changing in #22 but just to highlight issues I have come across when trying to load it.
1. The first header is `NRS_TRIP_CODE` when it should be `TRIP_CODE` to be consistent with the other files
2. There are commas in the comments which cause problems with `read_csv`. For example "salp and jelly, removed salp" is read as two columns, when it should be one (`TSS_COMMENTS`)

**Comment by clairedavies** [comment]
sorted thanks for pointing out
